name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    env:
      NO_AVX: 1
      NO_AVX2: 1
      ATEN_CPU_CAPABILITY: default

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    

    steps:

    - name: checkout repo
      uses: actions/checkout@v4
    - name: Set up Python 3.9 (32-bit)
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        architecture: 'x86'
    - name: Show current directory and list files before extraction
      run: |
        echo "Current directory: $(pwd)"
        echo "Listing root directory contents:"
        ls
    
    - name: Extract ZIP archive
      run: |
        Expand-Archive -LiteralPath "D:\a\pytorch\pytorch\build.zip" -DestinationPath "D:\a\pytorch\pytorch\build"

    - name: Show current directory and list files after extraction
      run: |
        echo "Current directory: $(pwd)"
        echo "Listing root directory contents:"
        ls
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        py -V
        # python -m pip install flake8 pytest
        python -m pip install -r requirements.txt
    - name: Setup MSVC Developer Command Prompt
      uses: TheMrMilchmann/setup-msvc-dev@v3.0.1
      with:
        arch: x86
            

    - name: Start Building
      run: |
        python -V
        python setup.py bdist_wheel
