# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Set up Python 3.9 (32-bit)
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        architecture: 'x86'
    - name: Show current directory and list files
      run: |
        echo "Current directory: $(pwd)"
        echo "Listing root directory contents:"
        ls
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        pip install -r requirements.txt
    - name: Set up MSVC for 32-bit
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x86

    - name: Start Building
      run: |
        py setup.py bdist_wheel
